/**
 * Conformance tests. These load vectors generated by the Python implementation and
 * assert the TypeScript side produces identical bytes and hashes. If any of these
 * fail, a certificate sealed in the browser would be rejected by the Python verifier,
 * which would break the whole product. This is the most important test file in the
 * browser layer.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import { canonicalString } from "../canonical.ts";
import { EventLog, textHashOf, type Event } from "../log.ts";

const here = dirname(fileURLToPath(import.meta.url));
const vectors = JSON.parse(readFileSync(join(here, "vectors.json"), "utf-8"));

test("canonical serialization matches Python vectors", () => {
  for (const v of vectors.canonical) {
    assert.equal(canonicalString(v.input), v.expected);
  }
});

test("text hashes match Python vectors", async () => {
  for (const v of vectors.text_hash) {
    assert.equal(await textHashOf(v.text), v.expected);
  }
});

test("event chain head matches Python vector", async () => {
  const log = new EventLog();
  for (const e of vectors.chain.events as Event[]) {
    await log.append(e);
  }
  assert.equal(log.head, vectors.chain.expected_head);
});

test("genesis hash matches", () => {
  assert.equal("0".repeat(64), vectors.chain.genesis);
});
